### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by zstyblik** [llgcode/draw2d#101]
Hello,

I've noticed there are couple copy-paste typos in documentation, resp. in documentation of `gc.go`.

Example:
```
    // SetLineJoin sets the current line join
    SetLineJoin(join LineJoin)
    // SetLineJoin sets the current dash
    SetLineDash(dash []float64, dashOffset float64)
    // ^^^ it should say SetLineDash
```

I can create a PR for those. May be this is a duplicate of #50?

**Comment by llgcode** [comment]
Hi @zstyblik yes you can create a PR with some doc typos referring this issue. thx
