### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by beefsack** [llgcode/draw2d#107]
I saw some discussion loosely related to SVG in #74 and #79, but am currently not seeing any other mentions of SVG in the README, issues or wiki.

Is there currently any plans to support SVG output?  I noticed a couple of people in the linked issues talking about starting work on it, have any of these made any progress?

SVG output feels like a very natural fit for this library.

**Comment by llgcode** [comment]
Hi @beefsack,
actually there's no plan to support SVG output today.  But if you want to contribute don't hesitate ;). So we could target a milestone

**Comment by Drahoslav7** [comment]
Hi,
I'd like to volunteer to implement support for SVG drawing context.

Do you have any particular suggestions in mind or anything I should consider before I start?
Or can I just try and see how will it go?

**Comment by llgcode** [comment]
Hi @Drahoslav7,
I really appreciate new contribution, I don't like to work alone :-).
 * The first thing to do is to print xml as text using the right encoding utf-8 by default. 
 * Do not use a third party lib to print xml to have control on how you want to print the svg. 
 * You can write the svg on the fly. 
 * Use group <g> for each transform/translate/rotate/scale. 
 * Write some unit test if possible.
 * I suggest draw2dsvg for the package name

You can send me a pull request so I can pull it locally. We can discuss about some technical part if you need to.

**Comment by Drahoslav7** [comment]
Thanks for tips.
I pretty much agree with your suggestions, but I'm not sure why shouldn't I use third party xml lib. Is it for better testability?
I was actually thinking about using https://github.com/ajstarks/svgo so I doesn't have to write everything from scratch.

My main reason I want to implement SVG context is that I'm using draw2d in my project (OpenGL application for visualisation of Petri nets) and I want to be able to export image to several different formats (png, pdf, svg, maybe even PostScript in the feature) while using the same interface for drawing.
So I'd prefer to take the path of least resistance.

**Comment by llgcode** [comment]
It's my opinion. Read svg is complex but generate svg is really simple and you don't need a full feature library like svgo to do it. I can help you generate path or transformation. I already work a lot with svg.
The other problem is that I don't want to multiply dependencies to other third party lib.
But this is your contribution, if you prefer using svgo no problem. And I'm sure it will work great.

**Comment by Drahoslav7** [comment]
After all, I decided not to use svgo. You are right, I will only use small subset of SVG specification (`<g>`, `<text>`, `<path>`,.. and probably just few other elements and thats it).

I will just use the standard `encoding/xml` package to encode svg.
I will create pull request soon, after I implement at last some part of the functionality.
