### ISSUE TITLE
draw2dpdf: No file created by call to SaveToPdfFile

### ISSUE THREAD

**Issue by Marneus68** [llgcode/draw2d#108]
Hi,

I have created a simple sample myself to validate the creation of pdf files from postscript files using [draw2d](https://github.com/llgcode/draw2d) in conjunction with [ps](https://github.com/llgcode/ps).

```go
package main

import (
        "github.com/llgcode/draw2d"
        "github.com/llgcode/draw2d/draw2dpdf"
        "github.com/llgcode/ps"
        "io/ioutil"
        "log"
        "os"
        "strings"
)

func main() {
        pdf := draw2dpdf.NewPdf("P", "mm", "A4")
        gc := draw2dpdf.NewGraphicContext(pdf)

        gc.Translate(0, 200)
        gc.Scale(0.35, -0.35)
        gc.Translate(70, -200)

        Draw(gc, "tiger.ps")
        gc.Restore()

        draw2dpdf.SaveToPdfFile("tiger.pdf", pdf)
}

func Draw(gc draw2d.GraphicContext, filename string) {
        // Open the postscript
        src, err := os.OpenFile(filename, 0, 0)
        if err != nil {
                log.Fatal(err.Error())
        }
        defer src.Close()
        bytes, err := ioutil.ReadAll(src)
        reader := strings.NewReader(string(bytes))

        // Initialize and interpret the postscript
        interpreter := ps.NewInterpreter(gc)
        interpreter.Execute(reader)
}
```

When trying to convert the [tiger.ps](https://raw.githubusercontent.com/llgcode/draw2d/master/resource/image/tiger.ps) (an exact copy of the one present in the examples provided with draw2d) no file is created and no error message is displayed on the standard output.

When replacing the file by a much simpler postscript file ([this one for instance](https://ftp.scsh.net/pub/scsh/contrib/fps/doc/examples/ps/fractal-sqr.ps)) it does create a pdf.

Am I doing something wrong or is this an unexpected behavior?

Additionally, is there any way to reliably test for errors when saving the pdf file?

**Comment by llgcode** [comment]
Hi @Marneus68 
I think you can test error like this
err := draw2dpdf.SaveToPdfFile("tiger.pdf", pdf)
if err != nil {
   // there's an error
}

**Comment by Marneus68** [comment]
Oops, that's silly on my part, I should have seen that.

Now that I did that I end up with the following error no matter what file I input:

    2016/09/01 22:42:02 error attempting to end transformation operation out of sequence

After a bit of research it seems this is an error caused by gopdf so I'm going to close this issue here and continue my research over there.

Thank your for your time and work and sorry for the inconvenience.

**Comment by llgcode** [comment]
It's ok.
if you open an issue in gopdf you can reference this issue. I leave it open so that I can track the issue. thanks

**Comment by Marneus68** [comment]
It seems that updating my local packages fixed the issue, I was using an outdated version of draw2d and gopdf.

Sorry for the inconvenience and thanks for the help!

**Comment by llgcode** [comment]
no prob. ;)
