### ISSUE TITLE
Move/Shift Entire Path

### ISSUE THREAD

**Issue by redstarcoder** [llgcode/draw2d#110]
A "Path.Shift" method would be very useful. This method would shift every point on the path by an x modifier and a y modifier. I'd imagine it'd look like this:

```go
// Shift moves every point in the path by x and y.
func (p *Path) Shift(x, y float64) {
	if len(p.Points) % 2 != 0 {
		panic("Invalid Path (odd number of points)")
	}
	for i := 0;i < len(p.Points);i += 2 {
		p.Points[i] += x
		p.Points[i+1] += y
	}
}
```

This would make it easy to save paths and move/reuse them later instead of rebuilding them all the time.

**Comment by llgcode** [comment]
I think it's better to use translate method that is dedicated for this kind of use.
gc.translate(x,y)

**Comment by redstarcoder** [comment]
The issue with translate is doesn't it affect the entire gc, not just the current path? I haven't touched matrixes at all yet, so I could be completely wrong. I want to use this method for features like storing a glyph's path (or a word), and basically blitting it onto the current path.

I wrote up an example here (it uses my fork for a couple functions): https://github.com/redstarcoder/cache2d/blob/master/text.go

I've just been looking at CPU usage so far instead of benchmarks (it's late), but it seems to be performing well. Is there a way I could implement something like this without modifying the library, or/and while using gc.translate?

**Comment by llgcode** [comment]
Interesting,
you can use gc.Save() and gc.Restore() to apply to your draw and restore to previous transformation.

Other methods of Path doesn't modify the path it self, there's already a matrix object that transform points. Careful There's a method ArcTo that add angle into Points slice, you may have to filter.
I'd prefer that a Path could not be modified but may be "transformable" into a new path.

**Comment by redstarcoder** [comment]
I actually use `gc.Save()` and `gc.Restore()` on the `renderGlyph` function for exactly that! This issue with doing this for every draw of every glyph though is that it copies the entire path in the background once (among a bunch of other stuff), which I feel could cause some slowdown for large paths.

That seems fair, I'll look into using matrixes.
Oh wow not sure how I missed that, thanks! That's really going to murder the simplicity of the method.
Hmm alright I'll definitely try to accomplish that and benchmark it against what I have now (with a couple changes).

------

I finally think I understand what the matrixes are doing on `draw2d`. So glossing over the fact that `draw2dgl` doesn't have `DrawImage` (which I guess I could copy over the `draw2dimg` implementation that uses `x/image/draw`)... I still think paths could be advantageous for uses such as this for the simple reason that they're small(er than images) and are easilly moved.

From what I gather, a path contains points and components to instruct the GPU what to draw, where, and how, and an image contains a bunch of specific points that must be passed to the GPU in full, where it then blits onto the screen (I guess vector vs raster?). At the very least, for the purposes of caching, a Shift method seems to be a huge win in terms of theoretical memory saved, and potentially performant for paths that would produce very large images (but otherwise be small paths).

Also how would I even produce an image to be transformed quickly on the fly? The only example of utilizing transformation matrixes seems to be for `image.Image` objects. I'd be happy to attempt to write the font cache stuff I have done so using matrix transformations and compare benchmarks but currently, I just really don't see how.

**Comment by redstarcoder** [comment]
A new comment because that last one became a bit of a disaster...

I've managed to successfully do a transformation, however I'm still not sure if it's going to be possible to achieve any sort of performance gain if I have to fill each glyph separately (that's the only way I saw to do a translation). I will try to produce some benchmarks for clarity.

**Comment by redstarcoder** [comment]
These are some hesitant benchmarks. They're still very unstable right now, but you appear to be correct, Translate might be the best way to do this (Rendering Path.Shift useless):

BenchmarkFillStringAt-4         	     200	  16395917 ns/op
BenchmarkFillStringAtCached-4   	     200	  10431932 ns/op
BenchmarkFillStringAtCachedTranslate-4   	     300	  10130143 ns/op

If I can't get the benchmarks more stable I'll put them up and let you look at them. I think there might be a memory leak for something to do with OpenGL somewhere which is causing the benchmarks to go crazy, but I'm not sure how to resolve that right now.

**Comment by redstarcoder** [comment]
Yup, this is it, thanks for considering it! Please enjoy the benchmarks, I hope to seamlessly integrate the cache improvements into draw2d soon (I mean, why not? It's 50% faster :p), and I'll make a new issue for that.

**Comment by llgcode** [comment]
Thanks @redstarcoder for your work. I hope to integrate your work soon
