### ISSUE TITLE
No Support for Gray Scale Image Type or YUV Scale Image Type

### ISSUE THREAD

**Issue by ashu1994** [llgcode/draw2d#114]
Is this library only support RGB format images. What to do if to use this library for gray images or yuv images?

**Comment by llgcode** [comment]
first constructor of draw2dimg support only RGBA. You can try the constructor with a specific painter https://github.com/llgcode/draw2d/blob/master/draw2dimg/ftgc.go#L68

**Comment by ashu1994** [comment]
This constructor has two arguments . What to pass as Painter . Either i have to myself add the implementation of Painter (Paint method and SetColor Method )interface for Gray/YUV images?

**Comment by ashu1994** [comment]
Have written this code for GrayScale Image Support. This is working fine now but but not sure that everything i did is right or it can give some errors.Please review it...

type Painter interface {
	raster.Painter
	SetColor(color color.Color)
}
type GrayPainter struct {
	// Image is the image to compose onto.
	Image *image.Gray
	cy    uint32
}

func NewGRAYPainter(m *image.Gray) *GrayPainter {
	return &GrayPainter{Image: m}
}
func (r GrayPainter) Paint(ss []raster.Span, done bool) {
	b := r.Image.Bounds()
	for _, s := range ss {
		if s.Y < b.Min.Y {
			continue
		}
		if s.Y >= b.Max.Y {
			return
		}
		if s.X0 < b.Min.X {
			s.X0 = b.Min.X
		}
		if s.X1 > b.Max.X {
			s.X1 = b.Max.X
		}
		if s.X0 >= s.X1 {
			continue
		}
		base := (s.Y-r.Image.Rect.Min.Y)*r.Image.Stride - r.Image.Rect.Min.X
		p := r.Image.Pix[base+s.X0 : base+s.X1]
		//color := 255
		for i := range p {
			p[i] = 255
		}
	}
}

**Comment by ashu1994** [comment]
func (r *GrayPainter) SetColor(c color.Color) {
	r.cy, _, _, _ = c.RGBA()
}

**Comment by llgcode** [comment]
Great, 
thanks. I can't integrate right now. 
Quick review:
What is r.cy?
I think that color need to be converted like this (not sure):
https://golang.org/src/image/image.go?s=21483:21528#L770

Is it possible that you open a PullRequest?

**Comment by ashu1994** [comment]
Thanks for the review . Yes the color need to be converted and I have changed it. And the r.cy is required  for the SetColor implementation as i need to further convert this image t jpeg and it is possible to set some other color as well. For now,it is just needed for implementing painter interface having setcolor functionality.

Here is my updated code. Yes i can open a pull request

type Painter interface {
	raster.Painter
	SetColor(color color.Color)
}
type GrayPainter struct {
	// Image is the image to compose onto.
	Image *image.Gray
	cy    uint8
}

func NewGRAYPainter(m *image.Gray) *GrayPainter {
	return &GrayPainter{Image: m}
}
func (r GrayPainter) Paint(ss []raster.Span, done bool) {
	b := r.Image.Bounds()
	for _, s := range ss {
		if s.Y < b.Min.Y {
			continue
		}
		if s.Y >= b.Max.Y {
			return
		}
		if s.X0 < b.Min.X {
			s.X0 = b.Min.X
		}
		if s.X1 > b.Max.X {
			s.X1 = b.Max.X
		}
		if s.X0 >= s.X1 {
			continue
		}
		base := (s.Y-r.Image.Rect.Min.Y)*r.Image.Stride - r.Image.Rect.Min.X
		p := r.Image.Pix[base+s.X0 : base+s.X1]
		color := r.cy
		for i := range p {
			p[i] = color
		}
	}
}

func (r *GrayPainter) SetColor(c color.Color) {
	c1 := color.GrayModel.Convert(c).(color.Gray).Y
	r.cy = c1
}

**Comment by llgcode** [comment]
Great I wait for your pull request

**Comment by ashu1994** [comment]
Can u give me access to push the code into a new branch under master.?

**Comment by ashu1994** [comment]
i dont have push access

**Comment by llgcode** [comment]
Seems to be a good tutorial on the subject. 
https://yangsu.github.io/pull-request-tutorial/
But if have trouble doing a"pull request" I can merge the code later

**Comment by ashu1994** [comment]
Hey...for creating a pull request i need to push my branch but it is showing u dont have access to push any changes..without pushing i cannot create a pull request.

**Comment by ashu1994** [comment]
I need to ask. I have made changes to paint.go file present in raster package. How to submit changes for that file?

**Comment by ashu1994** [comment]
i have made necessary changes in paint.go as well and created a pull request for that too. These both changes need to be there for proper running of code.
