### ISSUE TITLE
Bounding box ingores kerning

### ISSUE THREAD

**Issue by kodabb** [llgcode/draw2d#119]
a recent update in bounding box computation made its width reduced: it looks like the old behaviour was more correct since only the antialias pixels are outside, see the attached picture

![drawtextdiff](https://cloud.githubusercontent.com/assets/1374357/19776547/7517436e-9c42-11e6-8367-824902a69319.png)

working bb 13548be874707c45a83f9c2c282d76d671c7acf8 (right)
tested bb 0d961cd2997a2d0c1c91645ab5e552bf60d4b49c (left)

**Comment by redstarcoder** [comment]
I'll look into this, the width shouldn't have changed at all.

**Comment by redstarcoder** [comment]
I see exactly what you mean now. The issue lies in "if hasPrev {" in `CreateStringPath`, because `hasPrev` is always false with the new method, causing drawing text to ignore kerning. I'll work on a solution, sorry about that!

**Comment by redstarcoder** [comment]
@kodabb, please test PR #120 and let me know if that resolves your issues!

**Comment by redstarcoder** [comment]
@kodabb, how do you produce those results? I've attached my results of 3 tests involving c120708, 0d961cd, and b9005c9. I'm clearly doing something wrong...

![3testcannotreproduce](https://cloud.githubusercontent.com/assets/22847904/19951447/761de60e-a134-11e6-801e-f3494190f7d4.png)

This is just drawing the text, returning the width produced by `FillStringAt`. Font is built with:

```go
gc.SetFontData(draw2d.FontData{
	Name:   "luxi",
	Family: draw2d.FontFamilyMono,
	Style:  draw2d.FontStyleBold})
gc.SetFontSize(14)
```

**Comment by kodabb** [comment]
Sorry I forgot about this, I'll check tomorrow and provide some code samples!

**Comment by kodabb** [comment]
confirmed fixed, thank you
