### ISSUE TITLE
gopkg.in import is broken

### ISSUE THREAD

**Issue by tboerger** [llgcode/draw2d#124]
Hi,

with the current code of `v1` the import paths are broken, as you can see at https://github.com/llgcode/draw2d/blob/v1/draw2dgl/gc.go#L11 the gopkg.in version imports `github.com/llgcode/draw2d`, but that have to be `gopkg.in/llgcode/draw2d.v1`.

Can somebody resolve that issue?

**Comment by llgcode** [comment]
Thanks @tboerger to report the issue. I removed the tag **v1** and open a branch **v1**. And then replaced github.com/llgcode/draw2d with gopkg.in/llgcode/draw2d.v1

Note that current master branch is stable, you can use it instead of the old one v1
