### ISSUE TITLE
Drawing mazes has weird issues w/ transparency, fill color.

### ISSUE THREAD

**Issue by venantius** [llgcode/draw2d#130]
Hey there. I'm working through [Mazes for Programmers](https://pragprog.com/book/jbmaze/mazes-for-programmers) and doing the code in Go instead of Ruby.

I've run into an issue where walls that I draw with only a single width are made transparent or otherwise filled inappropriately, and I can't figure out what I'm doing wrong, so I thought I'd ask for help. 

First, an image to show what I'm talking about:

![derp](https://cloud.githubusercontent.com/assets/1824859/21869446/864d0c62-d80c-11e6-8e8a-98476331bae6.png)

An enlarged version for easier inspection:

<img width="382" alt="screen shot 2017-01-11 at 2 49 52 pm" src="https://cloud.githubusercontent.com/assets/1824859/21869611/4425b6e4-d80d-11e6-8ccc-829335beef78.png">

Note that, for instance, the left and top sections are completely solid but the right and bottom sections are both transparent and seem to actually take up 2 pixels (except for a section on the bottom wall over to the right, which is both two-pixels wide AND clearly solid). All of the interior walls are transparent.

The code that generated this is below. Note that the stroke color is set to black, width is set to 1 and the fill color is red, but transparent. We also iterate through all of the pixel points and set them to white as a preprocessing step (aside: I'm sure there's a better way to do this and would love to know how). 

```golang
func (g *grid) ToPNG(cellSize int) {
	imgWidth := cellSize * g.columns;
	imgHeight := cellSize * g.rows;

	img := image.NewRGBA(image.Rect(0, 0, imgWidth + 1, imgHeight + 1));

	gc := draw2dimg.NewGraphicContext(img);
	gc.SetFillColor(color.RGBA{0xff, 0x00, 0x00, 0x00});
	gc.SetStrokeColor(color.RGBA{0x00, 0x00, 0x00, 0xff});
	gc.SetLineWidth(1);

	// First, set the background
	for x := 0; x <= imgWidth; x++ {
		for y := 0; y <= imgHeight; y++ {
			img.Set(x, y, color.RGBA{0xff, 0xff, 0xff, 0xff})
		}
	}

	for c := range g.Cells() {
		x1 := c.column * cellSize;
		y1 := c.row * cellSize;
		x2 := (c.column + 1) * cellSize;
		y2 := (c.row + 1) * cellSize;

		if c.north == nil {
			gc.MoveTo(float64(x1), float64(y1));
			gc.LineTo(float64(x2), float64(y1));
		}
		if c.west == nil {
			gc.MoveTo(float64(x1), float64(y1));
			gc.LineTo(float64(x1), float64(y2));
		}

		if !c.IsLinked(c.east) {
			gc.MoveTo(float64(x2), float64(y1));
			gc.LineTo(float64(x2), float64(y2));
		}

		if !c.IsLinked(c.south) {
			gc.MoveTo(float64(x1), float64(y2));
			gc.LineTo(float64(x2), float64(y2));
		}
	}
	gc.Close();
	gc.FillStroke();

	draw2dimg.SaveToPngFile("derp.png", img);
}
```

Now, if I comment out the part of the code that sets the background to white, something interesting happens - we start seeing red in some of the walls:

![derp](https://cloud.githubusercontent.com/assets/1824859/21870287/790441d4-d810-11e6-890c-b1407cc08d1e.png)

Enlarged:

<img width="361" alt="screen shot 2017-01-11 at 3 13 44 pm" src="https://cloud.githubusercontent.com/assets/1824859/21870305/8e81b7a8-d810-11e6-84c7-364604327cd5.png">

A few different questions, I guess:

1. Why aren't my walls 1 pixel thick all the time?
2. Why are they transparent? (presumably related to 1)
3. Why does a 0-alpha red fill show up ever?
4. How can I change this to just show single-pixel lines that are actually solid? :)

Thanks!

**Comment by llgcode** [comment]
- Why aren't my walls 1 pixel thick all the time?
this is due to subpixel accuracy, if you want to display lines maller than a pixel

- Why are they transparent? (presumably related to 1)
subpixel accuracy uses transparency 

- Why does a 0-alpha red fill show up ever?
 I think you compose these two color color.RGBA{0xff, 0x00, 0x00, 0x00} color.RGBA{0x00, 0x00, 0x00, 0xff}. You might want to just stroke: gc.Stroke()

- How can I change this to just show single-pixel lines that are actually solid? :)
I think you can accomplish this by translating your draw by 0.5 (no tested): gc.Translate(0.5, 0.5)

**Comment by venantius** [comment]
Thanks for the answers! I couldn't get this to work in a way that I expected so I've decided to just work directly with the Go image library.

**Comment by llgcode** [comment]
You may find some useful helpers here:
https://godoc.org/golang.org/x/image
