### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by ChristophPech** [llgcode/draw2d#131]
I am using draw2d inside a webservers HTTP handler getting crashes due to thread safety issues inside the font cache:

`fatal error: concurrent map read and map write

goroutine 27939 [running]:
runtime.throw(0xb0976d, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc468f1cdd0 sp=0xc468f1cdb0
runtime.mapaccess1_fast32(0xa5f9a0, 0xc467ed10b0, 0xc400000034, 0x29)
	/usr/local/go/src/runtime/hashmap_fast.go:21 +0x1a4 fp=0xc468f1cdf8 sp=0xc468f1cdd0
github.com/llgcode/draw2d/draw2dbase.FetchGlyph(0xfc8420, 0xc464f8b270, 0xc47561b8c0, 0x29, 0x3fd2000000000034, 0xc022900000000000)
	/home/chp/project/src/github.com/llgcode/draw2d/draw2dbase/text.go:16 +0xd4 fp=0xc468f1ce88 sp=0xc468f1cdf8
github.com/llgcode/draw2d/draw2dimg.(*GraphicContext).StrokeStringAt(0xc464f8b270, 0xc47ef57048, 0x1, 0x40564d8000000000, 0x40542a0000000000, 0x401f700000000000)
	/home/chp/project/src/github.com/llgcode/draw2d/draw2dimg/ftgc.go:166 +0x1c1 fp=0xc468f1cf10 sp=0xc468f1ce88
main.MapRender(0x1d5b7, 0xc46351420d, 0x5, 0x100, 0x100, 0x404a44a4985365c0, 0x402ab80000000000, 0x404a465a79921640, 0x402ac34000000000, 0xc463514258, ...)
	/home/chp/project/src/project/maprender.go:1256 +0x3790 fp=0xc468f1d860 sp=0xc468f1cf10
main.(*MapRenderHandler).ServeHTTP(0xff8868, 0xfc1760, 0xc47561b740, 0xc4635143c0)
	/home/chp/project/src/project/web.go:376 +0x10e0 fp=0xc468f1db90 sp=0xc468f1d860
`

I already did a fork and fixed the issue, but this not fork/pull-request compatible due to the self-referential imports: https://github.com/ChristophPech/draw2d

**Comment by gerald1248** [comment]
@ChristophPech Shlomi Noach has a good writeup for the go import/pull request problem.

**Comment by ChristophPech** [comment]
Thanks, I didn't know that.
This method conflicts with my deploy system but nontheless, I added a pull-request.

**Comment by ChristophPech** [comment]
I see, there is already a discussion going on about the thread safety and the glyph cache, here are my 2 cents:

Making the glyph cache replacable just adds unnessesary complexity and gains nothing, in fact it adds another pointer dereference which can lead to another memory cache miss.

Using a mutex in a single threaded application will also have the cost of a cache miss because internally it is a "lck xchg". Compared to all the rendering this won't even be measurable in any real world application.

Trying a go-canonical approach using channels sounds beautiful but in the end it will be slower than a mutexed cache. The fastest way is using a RWMutex to allow concurrent reads because there are significantly more reads than writes.

Look for example at this well done LRU cache: https://github.com/patrickmn/go-cache
You might even use it for draw2d

**Comment by llgcode** [comment]
Ok I need to test the 2 approach. 
Your help is really appreciated.
Laurent

**Comment by nilptr** [comment]
I got the same issue when use draw2d to implement a captcha service. @ChristophPech ChristophPech's fix works fine for me.
I would appreciate it if this issue is solved ;-)

**Comment by llgcode** [comment]
Thanks @nilptr,
I have 2 pull request on this subject. Not sure if I integrate this pull request or the other one
regards.

**Comment by ChristophPech** [comment]
This is a good step in the right direction. But it is still non-obvious to any user of this library that it is not thread safe.
In golang any package is threadsafe by default except this one. Therefore the default should be either a new FontCache for every GraphicContext or a thread safe one.

**Comment by llgcode** [comment]
Thanks @ChristophPech for your quick comment. I agree but there's a lot of packages using SetFontFolder, and I don't want to break API. 
https://github.com/search?q=draw2d.SetFontFolder&type=Code&utf8=%E2%9C%93

**Comment by llgcode** [comment]
this will fix this problem fixed in gonum/plot@6bb95dd

**Comment by Drahoslav7** [comment]
Good job @llgcode 

Unfotunately these changes broken `draw2dgl`. It won't compile.
```
# github.com/llgcode/draw2d/draw2dgl
..\..\..\github.com\llgcode\draw2d\draw2dgl\gc.go:220: undefined: draw2dbase.FetchGlyph
..\..\..\github.com\llgcode\draw2d\draw2dgl\gc.go:286: undefined: draw2dbase.FetchGlyph
```
Could you please take a look at this?

**Comment by llgcode** [comment]
thanks @Drahoslav7 
I was on my win laptop and did not installed mingw gcc to install properly gl packages. So I haven't compiled/tested yet for opengl.
Sorry for the inconvenience.

**Comment by llgcode** [comment]
The compilation issue is now fixed
