### ISSUE TITLE
custom font cache in draw2dgl

### ISSUE THREAD

**Issue by Drahoslav7** [llgcode/draw2d#136]
Hi @llgcode, thanks for that quick fix of the [draw2dgl compile error](https://github.com/llgcode/draw2d/issues/131#issuecomment-350586791).

However, my code is broken now.
I am using custom font cache for loading fonts from byte array (as described here: https://github.com/llgcode/draw2d/issues/127#issuecomment-267845074)

But now after recent changes, it does not work. Texts are not rendered at all and I got this error: `2017/12/11 13:19:14 open ..\resource\font\luxisr.ttf: The system cannot find the path specified.`  - even though I do not even use that font.

Could you please point me in the right direction on what should I change?

I guess I have to implement custom glyph cache too?

**Comment by Drahoslav7** [comment]
Edit:
I'm looking at your changes, and it seems there is problem in your code.

I think, that `draw2d.GetGlobalFontCache()` should be returning `fontCache` and not `defaultFonts`.

Or is there any other way how to use custom font cache in `drawd2gl` now?

**Comment by llgcode** [comment]
Ok I didn't realize that there were 2 globals, I've forgotten this important detail.
you can use a custom font cache by setting the public member gc.FontCache:
gc.FontCache = yourFontCache

gc have to be a draw2dgl.GraphicContext

globals are evil !
grr

There is so many side effects!!
Thank you for your help.

**Comment by Drahoslav7** [comment]
Nice. Thanks for the fix. :ok_hand:
