### ISSUE TITLE
Is it possible to fill path with transparent color on a non-transparent background?

### ISSUE THREAD

**Issue by hexdigest** [llgcode/draw2d#168]
What I'm trying to do is basically cutting a hole in a non-transparent background and it doesn't seem to work (which is kind of expected). Is it even possible to do this using this package?

**Comment by llgcode** [comment]
Hi @hexdigest,
the draw2dimg package use by default this [painter](https://github.com/golang/freetype/blob/master/raster/paint.go#L117).

You can overload the painter using [NewGraphicContextWithPainter](https://github.com/llgcode/draw2d/blob/master/draw2dimg/ftgc.go#L70). 

I guess if you set RGBAPainter Op attribute to **draw.Src** (by default **draw.Over**), it could work.
