### ISSUE TITLE
GetStringBounds Wrapping Support

### ISSUE THREAD

**Issue by wiless** [llgcode/draw2d#169]
Thanks a lot for the excellent, library. I use for generating image for e-Ink display ( waveshare).  The GetStringBounds function is useful for center aligning before rendering the string with given font setting. on the eInk displays. Please suggest, if you can add a function for enabling word-wrap. 

For e.g.  
gc.EstimateLines(str string, maxwidth int)

**Comment by llgcode** [comment]
Hi Wiles,
Great to see it is useful :-).
I guess It could be a function that take, a gc in parameter like this:
EstimateLines(gc Gc, str string, maxwidth int)

This function will use gc.GetStringBounds

**Comment by wiless** [comment]
> Hi Wiles,
> Great to see it is useful :-).
> I guess It could be a function that take, a gc in parameter like this:
> EstimateLines(gc Gc, str string, maxwidth int)
> 
> This function will use gc.GetStringBounds

Thanks, I managed with quick fix 
https://github.com/wiless/waveshare/blob/83a0643efa61308a0c33186c6683789bcad92db9/example/clock/main.go#L207
