### ISSUE TITLE
i know how to draw a line. but how do you draw a pixel? just 1 pixel.

### ISSUE THREAD

**Issue by hiqsociety** [llgcode/draw2d#176]
i know how to draw a line. but how do you draw a pixel? just 1 pixel.

is there an easy way to draw just 1 pixel?

setting a color to 1 pixel location

**Comment by llgcode** [comment]
Hi,
This is a vector draw library that target other format than raster image like svg, pdf. Pixel is not part of the definition of the library. If you want draw something that feel like a pixel you can draw a rectangle or a circle at a small size, depending on the unit you choose. 
You can also want to set a pixel with the golang image package that has al the function you need to manipulate a raster image.
I guess if you want a library that draw on a raster image only you may want to use this [one](https://github.com/fogleman/gg). This package has vectorial draw function and also image manipulation features.
