### ISSUE TITLE
How `Path ` info are transferred to the `github.com/golang/freetype/raster`

### ISSUE THREAD

**Issue by Megidd** [llgcode/draw2d#189]
# Question

What I'm trying to figure out now:

How `github.com/llgcode/draw2d/draw2dimg` package transfers its `Path        *draw2d.Path` info to the `github.com/golang/freetype/raster` package. For some reason, I cannot find any transfer of `Path` info.

# Details

The statement which triggers the painting process of `github.com/golang/freetype/raster` is the following:

https://github.com/llgcode/draw2d/blob/0ed1ff131195ddb59f6c689414724fe25436d2fc/draw2dimg/ftgc.go#L305

The `Path` info is stored by this field:

https://github.com/llgcode/draw2d/blob/0ed1ff131195ddb59f6c689414724fe25436d2fc/draw2dbase/stack_gc.go#L24

**Comment by llgcode** [comment]
Hi @Megidd,
it is done [here](https://github.com/llgcode/draw2d/blob/0ed1ff131195ddb59f6c689414724fe25436d2fc/draw2dimg/ftgc.go#L339) the draw2d path is transformed using `FtLineBuilder{Adder: gc.fillRasterizer}` that is able to transform a draw2d path to a [freetype raster.Adder](https://github.com/llgcode/draw2d/blob/0ed1ff131195ddb59f6c689414724fe25436d2fc/draw2dimg/ftpath.go#L12)

regards
