### ISSUE TITLE
Deprecate https://code.google.com/p/draw2d/

### ISSUE THREAD

**Issue by stanim** [llgcode/draw2d#70]
Unfortunately https://code.google.com/p/draw2d/ is number one on Google searches and still widely used.

We could take the following actions to deprecate the all repositories:
1. Do pull requests for projects importing the old repo: http://godoc.org/code.google.com/p/draw2d/draw2d?importers
2. Do a http redirect to this github repo: https://github.com/jung-kurt/gofpdf/issues/31

Pull requests:
- all Arrow packages: https://github.com/Arrow/display/pull/1
- https://github.com/vdobler/chart/pull/18

**Comment by llgcode** [comment]
I've send a email to google support asking us to redirect to https://github.com/llgcode/draw2d.
