### ISSUE TITLE
single pixel line images

### ISSUE THREAD

**Issue by emicklei** [llgcode/draw2d#77]
i am creating a transparent image with a grid pattern of lines.
The image size in 400x400 and I draw black lines every 10 pixels.

Close inspection of the resulting image shows that each line is taking 2 gray pixels with the execption of the "border" horizontal and vertical lines.

I suspect the rasterizer is responsible for this. Is it possible to tell the GC to draw sharp, single pixel,  lines?

thanks

**Comment by llgcode** [comment]
try gc.translate(0.5,0.5) so that you don't have subpixel antialiasing
rendering side effect

-- Laurent.

**Comment by emicklei** [comment]
yes, that's it. thanks again.
