### ISSUE TITLE
draw2.v1: draw2d.Circle() draws a horizontal line.

### ISSUE THREAD

**Issue by KoichiWada** [llgcode/draw2d#81]
I tried the code below with draw2d.v1 and got a result:
![circ](https://cloud.githubusercontent.com/assets/1043491/9514316/f53c0daa-4cd3-11e5-9955-50cd2dc9e132.png)

I think this is a bug. Could you check this?

```
package main

import (
	"gopkg.in/llgcode/draw2d.v1"
	"image"
	"image/color"
)

func main() {
	width := 200
	height := 200
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	gc := draw2d.NewGraphicContext(img)

	gc.SetStrokeColor(color.NRGBA{255, 255, 255, 255})
	gc.SetFillColor(color.NRGBA{255, 255, 255, 255})
	gc.Clear()

	gc.SetStrokeColor(color.NRGBA{255, 0, 0, 255})
	gc.SetLineWidth(1)

	// Draw a circle
	draw2d.Circle(gc, 100, 100, 50)
	gc.Stroke()

	draw2d.SaveToPngFile("circ.png", img)
}
```

**Comment by llgcode** [comment]
I tried to reproduce the bug in the master head and it seem to work. For now draw2d.v1 is frozen.

**Comment by KoichiWada** [comment]
I confirmed master is ok. I'll switch from v1 to master. Thanks.

**Comment by llgcode** [comment]
I added a test https://github.com/llgcode/draw2d/blob/master/draw2dkit/draw2dkit_test.go
Thanks @KoichiWada
