### ISSUE TITLE
Postscript Interpreter Error

### ISSUE THREAD

**Issue by scisci** [llgcode/draw2d#90]
trying the following with the sample .ps

```
// Initialize and interpret the postscript
interpreter := ps.NewInterpreter(gc)
interpreter.Execute(bytes.NewBufferString(logo))
```

`panic: interface conversion: interface is []ps.Value, not draw2d.Matrix`

**Comment by scisci** [comment]
hmm the postcript had a concat command in there so I think that's what was doing it. I'm noticing you can't really pass just any postscript to the interpreter, so I feel like you should list how to create a valid postscript file. I can't seem to generate one with adobe illustrator. can only make one by hand.

**Comment by llgcode** [comment]
can you please reopen the issue and attach one file that don't pass?
thx

-- Laurent.
