### ISSUE TITLE
When doing go get, getting unrecognized import path

### ISSUE THREAD

**Issue by Janardhan-Babu** [llgcode/draw2d#97]
Hi,

I am go newbie getting unrecognized import path when trying to import draw2d. I am using Windows 7 OS. 

**_D:\Projects\Go>go get -u gopkg.in/llgcode/draw2d.v1
package gopkg.in/llgcode/draw2d.v1: unrecognized import path "gopkg.in/llgcode/d
raw2d.v1"

D:\Projects\Go>go get -u github.com/llgcode/draw2d
package golang.org/x/image/math/fixed: unrecognized import path "golang.org/x/im
age/math/fixed"
package golang.org/x/image/font: unrecognized import path "golang.org/x/image/fo
nt"_**

Go version installed is 1.5
Go is installed in C:\go directory and in Path variable i have added "C:\go\bin"
GOPATH is set to "D:\Projects\Go"

Can you please help me out.

**Comment by llgcode** [comment]
Hi,
go get may not update other packages
try to update golang.org/x/image/ too 

    go get -u golang.org/x/image

cheers

**Comment by Janardhan-Babu** [comment]
Thanks it worked :)

**Comment by llgcode** [comment]
:)

**Comment by IgorGanapolsky** [comment]
@llgcode I am unable to run **go get -d -u gobot.io/x/gobot/...**
I get:
> package gobot.io/x/gobot/...: unrecognized import path "gobot.io/x/gobot/..."

**Comment by llgcode** [comment]
@IgorGanapolsky Not sure I could help. What is gobot?

**Comment by IgorGanapolsky** [comment]
@llgcode It it just another go library for IoT: https://gobot.io
